//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyTechCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubmitterName { get; set; }
        public Nullable<bool> FeedbackSubmitted { get; set; }
        public Nullable<int> FeedbackId { get; set; }
        public string FeedbackSubmittedBy { get; set; }
    }
}
